### ISSUE TITLE
Satisfactory updates

### ISSUE THREAD

**Issue by P4sca1** [IPS-Hosting/game-images#13]
- `-GamePort` has been renamed to `-Port`
- IPv6 support (do we need to change anything within Docker to support IPv6?)
- New way to only use the Query port, which comes at the cost of a packet router.
- Add option to enable `-DisablePacketRouting`. Also find out, when it is required and when it can be safely disabled.

https://satisfactory.fandom.com/wiki/Dedicated_servers#History

**Comment by Mattzi** [comment]
https://satisfactory.fandom.com/wiki/Multiplayer#Performance

**Comment by P4sca1** [comment]
Maybe this image should set the network quality to ultra by default and provide an env variable setting to configure it.
I found another image for satisfactory, which alles setting some of the .ini settings via env variables: https://github.com/wolveix/satisfactory-server#environment-variables
We could take a similar approach. However, I don't want the image to require root privileges (as the one linked does).

**Comment by P4sca1** [comment]
The changes are now implemented. Changing the config files (`.ini`) via env variables is not supported yet.
