### ISSUE TITLE
Settings location

### ISSUE THREAD

**Issue by Torkiwi** [IPS-Hosting/game-images#8]
Hello
I cant figure out where the config files are hidden..
I really dont known Vime or docker so I'm a bit lost.

If i add the  
```
-v /home/vrserver:/home/ips-hosting 
```
When creating the container I get this error on docker start
```
mkdir: cannot create directory '/home/ips-hosting/steamapps': Permission denied
```

Could you give me some precision on how/where I can access the server settings ? (ServerHostSettings.json, save files,...)

Thanks !

**Comment by P4sca1** [comment]
The user inside the container needs to have access to the files on the host system.
The default user inside the container has the id 1000. So you have 2 choices here:

1. Change the owner of the folder and all files within `/home/vrserver` to the user with the id 1000. **OR:**
2. Use another user to run the docker container. When creating or running the container with `docker run` or `docker create`, specify the `--user USERID` flag. USERID should be the owner of the files in `/home/vrserver`.

After the server started successfully, it will create a folder `/home/vserver/data`. Inside that folder, you can create a folder `Settings` and in that folder you can create a the json files (e.g. `ServerHostSettings.json`) and overwrite settings there.

**Comment by Torkiwi** [comment]
I guess Im getting closer..
So I went with option 2
The folder gets created in `/home/vserver/data`  
but
i'm now havong struggle with wine

```
Success! App '1829350' fully installed.
xvfb-run -a wine VRisingServer.exe -persistentDataPath ./data
it looks like wine32 is missing, you should install it.
multiarch needs to be enabled first.  as root, please
execute "dpkg --add-architecture i386 && apt-get update &&
apt-get install wine32"
wine: '/' is not owned by you, refusing to create a configuration directory there
```

I've installed, re-installed wine a dozen times but to no avail..
Not sure where I've gone wrong. Probably something to do with root but not sure how to fixed this mess.
Any ideas ? =D

**Comment by P4sca1** [comment]
How are you running the container now?
Can you send the command, please?
Also, what is the results of `ls -la /home/vrserver/`?

**Comment by Torkiwi** [comment]
```
root@demo2:~# ls -la /home/vrserver/
total 28
drwxr-xr-x  3 vrserver vrserver 4096 May 26 02:56 .
drwxr-xr-x 14 root     root     4096 May 25 09:19 ..
-rwxr-xr-x  1 vrserver vrserver 3820 May 26 02:48 .bash_history
-rwxr-xr-x  1 vrserver vrserver  220 May 15  2017 .bash_logout
-rwxr-xr-x  1 vrserver vrserver 3526 May 15  2017 .bashrc
drwxr-xr-x  5 vrserver vrserver 4096 May 26 02:45 data
-rwxr-xr-x  1 vrserver vrserver  807 Apr 18  2019 .profile
```

For the container:

to create  it
```
docker create -it --restart always \
  --name vrising-server \
  -p 27015:27015/udp \
  -p 27016:27016/udp \
  -v /home/vrserver/data:/home/ips-hosting \
  --user  1011 \
  ipshosting/game-vrising:v1
```
And to run it
`docker start vrising-server`

**Comment by Torkiwi** [comment]
So little update,
I decided to go with option 1 : `Change the owner of the folder and all files within /home/vrserver to the user with the id 1000`
Suddenly everything started to work. The server booted up !

But I cannot get to logon.

 I've added 27015 et 27016 to ufw rules, rebooted to be sure everything was ok
 But still I cant connect directly with ip:27015

So I disabled UFW to try again and still I cant connect..
I dont understand how/why ?
Did you run into this problem?

**Comment by P4sca1** [comment]
Do you try to directly connect via steam or in game? In the Steam server list, you need to add your server with port 27016. Ingame you need to use 27015. I am able to successfully connect to the server using this image.

**Comment by Torkiwi** [comment]
I tried both..
`Server not responding` from steam server.
As far as I can tell, the docker is running fine, the ports 27015 and 27016 are open but from what I read, docker creates its own rules so opening ports is not needed.
Im having the same unresponsiveness when I try other docker for vrising server.
I'm out of idea on how to debug this^^

I guess my first question has been answered. (Where is the config folder hiding)
